CC= g++

CFLAGS = -Wall -Werror -ansi -pedantic

all:
	mkdir -p ./bin
	$(CC) $(CFLAGS) ./src/main.cpp -o ./bin/rshell

main:
	$(CC) $(CFLAGS) ./src/main.cpp

Tree:
	$(CC) $(CFLAGS) ./src/Tree.cpp

Test:
	$(CC) $(CFLAGS) ./src/Test.cpp

Connector:
	$(CC) $(CFLAGS) ./src/Connector.cpp

In:
	$(CC) $(CFLAGS) ./src/In.cpp

OutOne:
	$(CC) $(CFLAGS) ./src/OutOne.cpp

OutTwo:
	$(CC) $(CFLAGS) ./src/Connector.cpp

Pipe:
	$(CC) $(CFLAGS) ./src/Connector.cpp

Cmd:
	$(CC) $(CFLAGS) ./src/Cmd.cpp

AND:
	$(CC) $(CFLAGS) ./src/AND.cpp

OR:
	$(CC) $(CFLAGS) ./src/OR.cpp

Semicolon:
	$(CC) $(CFLAGS) ./src/Semicolon.cpp

Exit:
	$(CC) $(CFLAGS) ./src/Exit.cpp